version: "3"


networks:
  my_network:
    driver: bridge
  


volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/psychom/Desktop/my_database
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/psychom/Desktop/wordpress

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
       - MYSQL_HOST=${MYSQL_HOST}
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
       - WORDPRESS_ROOT_PASSWORD=${WORDPRESS_ROOT_PASSWORD}
    image: mariadb
    container_name: MARIADB
    networks:
      - my_network
    volumes:
      - mariadb_data:/home/psychom/Desktop/my_database
    restart: unless-stopped

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: WORDPRESS
    networks:
      - my_network
    volumes:
      - wordpress_data:/var/www/wordpress:rw
    depends_on:
       - mariadb
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: NGINX
    depends_on:
     - wordpress
    ports:
      - "443:443"
    networks:
      - my_network
    volumes:
      - wordpress_data:/var/www/wordpress:ro
    restart: unless-stopped