FROM debian:buster

RUN apt-get update && \
    apt-get install -y \
    wget \
    unzip \
    curl
RUN apt-get install -y php7.3-fpm php7.3-mysql php7.3-json php7.3-xmlrpc php7.3-curl php7.3-gd php7.3-xml php7.3-mbstring expect 
RUN wget http://wordpress.org/latest.tar.gz
RUN tar xfz latest.tar.gz &&  rm -rf latest.tar.gz
RUN mv wordpress/ /var/www/html/ && cd /var/www/html/
RUN mv /var/www/html/wordpress/* ./ && rm -rf wordpress
RUN chmod +x /tools/script.sh
